import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Providers } from "../Provider";
import Navigation from "@/components/Navigation";
import CheckInStatus from "@/components/CheckInStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WithNavbarLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="min-h-screen bg-neutral-900 text-neutral-200">
            <nav className="border-b border-neutral-700 bg-neutral-800 px-6 py-4">
              <div className="flex items-center justify-between">
                {/* Company Logo */}
                <div className="text-xl font-semibold">Company Logo</div>

                {/* Navigation Tabs */}
                <Navigation />

                <CheckInStatus />
              </div>
            </nav>

            <main className="container mx-auto px-6 py-8">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
